# Generated by Django 6.0.3 on 2026-04-29 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='назва')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'категорія',
                'verbose_name_plural': 'категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='опис')),
                ('image', models.ImageField(upload_to='shop/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='shop/thumbnail/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публікації')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
    ]
