# Generated by Django 6.0.3 on 2026-04-13 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'категорія',
                'verbose_name_plural': 'категорії',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='назва')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='опис')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публікації')),
                ('image', models.URLField(default='https://img.freepik.com/free-vector/user-blue-gradient_78370-4692.jpg')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='категорія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('tag', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'новина',
                'verbose_name_plural': 'новини',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Коментар:', max_length=30)),
                ('content', models.TextField(default='', max_length=100, verbose_name='опис')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публікації')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'коментарі',
            },
        ),
    ]
