# Generated by Django 6.0.3 on 2026-04-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='імʼя')),
                ('email', models.EmailField(max_length=254, verbose_name='пошта')),
            ],
        ),
    ]
