# Generated by Django 6.0.3 on 2026-04-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'підписка', 'verbose_name_plural': 'підписки'},
        ),
    ]
