# Generated by Django 6.0.3 on 2026-04-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='blog_profile/user_profile.png', upload_to='blog_profile/'),
        ),
    ]
